import type { Category, Product } from "./types.js";

export const categoriesSeed: Category[] = [
  { id: "breakfast", title: "Утро без суеты", sortOrder: 10, isVisible: true },
  { id: "dinner", title: "Ужин за 15 минут", sortOrder: 20, isVisible: true },
  { id: "stock", title: "Всегда должны быть в морозилке", sortOrder: 30, isVisible: true },
  { id: "kids", title: "Для супа и ужина", sortOrder: 40, isVisible: true }
];

const productImage = (filename: string) => `images/products/${filename}`;

export const productsSeed: Product[] = [
  {
    id: "syrniki-1kg",
    categoryId: "breakfast",
    title: "Сырники классические",
    description: "Классические домашние сырники для спокойного и вкусного завтрака.",
    price: 600,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("syrniki-assorted.jpg"),
    stock: 18,
    isVisible: true,
    sortOrder: 10
  },
  {
    id: "syrniki-hearts",
    categoryId: "breakfast",
    title: "Сырники-сердечки с соком вишни и апельсиновой цедрой",
    description: "Домашние сырники в форме сердечек с вишневым соком и ароматной апельсиновой цедрой.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("syrniki-assorted.jpg"),
    stock: 12,
    isVisible: true,
    sortOrder: 20
  },
  {
    id: "kids-cocoa-syrniki",
    categoryId: "breakfast",
    title: "Сырники с какао",
    description: "Домашние сырники с какао и мягким шоколадным вкусом.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("syrniki-assorted.jpg"),
    stock: 10,
    isVisible: true,
    sortOrder: 30
  },

  {
    id: "pork-cutlet",
    categoryId: "dinner",
    title: "Котлеты из свинины",
    description: "Сочные домашние котлеты из свинины для быстрого ужина.",
    price: 70,
    unit: "100g",
    unitLabel: "100 г",
    imageUrl: productImage("cutlets-meat.jpg"),
    stock: 45,
    isVisible: true,
    sortOrder: 10
  },
  {
    id: "chicken-cutlet",
    categoryId: "dinner",
    title: "Котлеты куриные",
    description: "Нежные домашние котлеты из курицы.",
    price: 80,
    unit: "100g",
    unitLabel: "100 г",
    imageUrl: productImage("cutlets-meat.jpg"),
    stock: 42,
    isVisible: true,
    sortOrder: 20
  },
  {
    id: "beef-pork-cutlet",
    categoryId: "dinner",
    title: "Котлеты говядина/свинина",
    description: "Домашние котлеты из говядины и свинины с насыщенным мясным вкусом.",
    price: 110,
    unit: "100g",
    unitLabel: "100 г",
    imageUrl: productImage("cutlets-meat.jpg"),
    stock: 20,
    isVisible: true,
    sortOrder: 30
  },
  {
    id: "beef-chicken-cutlet",
    categoryId: "dinner",
    title: "Котлеты говядина/курица",
    description: "Домашние котлеты из говядины и курицы.",
    price: 110,
    unit: "100g",
    unitLabel: "100 г",
    imageUrl: productImage("cutlets-meat.jpg"),
    stock: 26,
    isVisible: true,
    sortOrder: 40
  },
  {
    id: "pike-cutlet",
    categoryId: "dinner",
    title: "Котлеты из щуки",
    description: "Нежные рыбные котлеты из щуки.",
    price: 140,
    unit: "100g",
    unitLabel: "100 г",
    imageUrl: productImage("cutlets-fish.jpg"),
    stock: 12,
    isVisible: true,
    sortOrder: 50
  },
  {
    id: "zander-cutlet",
    categoryId: "dinner",
    title: "Котлеты из судака",
    description: "Домашние рыбные котлеты из судака.",
    price: 250,
    unit: "100g",
    unitLabel: "100 г",
    imageUrl: productImage("cutlets-fish.jpg"),
    stock: 9,
    isVisible: true,
    sortOrder: 60
  },

  {
    id: "pork-dumplings",
    categoryId: "stock",
    title: "Пельмени со свининой",
    description: "Домашние пельмени ручной лепки со свининой.",
    price: 600,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("dumplings-assorted.jpg"),
    stock: 20,
    isVisible: true,
    sortOrder: 10
  },
  {
    id: "chicken-dumplings",
    categoryId: "stock",
    title: "Пельмени с курицей",
    description: "Домашние пельмени ручной лепки с курицей.",
    price: 650,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("dumplings-assorted.jpg"),
    stock: 22,
    isVisible: true,
    sortOrder: 20
  },
  {
    id: "beef-pork-dumplings",
    categoryId: "stock",
    title: "Пельмени говядина/свинина",
    description: "Домашние пельмени ручной лепки с говядиной и свининой.",
    price: 800,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("dumplings-assorted.jpg"),
    stock: 16,
    isVisible: true,
    sortOrder: 30
  },
  {
    id: "beef-chicken-dumplings",
    categoryId: "stock",
    title: "Пельмени говядина/курица",
    description: "Домашние пельмени ручной лепки с говядиной и курицей.",
    price: 800,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("dumplings-assorted.jpg"),
    stock: 14,
    isVisible: true,
    sortOrder: 40
  },
  {
    id: "potato-vareniki",
    categoryId: "stock",
    title: "Вареники с картофелем",
    description: "Домашние вареники с картофельной начинкой.",
    price: 300,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("vareniki-potato-cottage.jpg"),
    stock: 18,
    isVisible: true,
    sortOrder: 50
  },
  {
    id: "cottage-cheese-vareniki",
    categoryId: "stock",
    title: "Вареники со сладким творогом",
    description: "Домашние вареники с нежной начинкой из сладкого творога.",
    price: 300,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("vareniki-potato-cottage.jpg"),
    stock: 19,
    isVisible: true,
    sortOrder: 60
  },
  {
    id: "potato-mushroom-vareniki",
    categoryId: "stock",
    title: "Вареники с картофелем и грибами",
    description: "Домашние вареники с картофелем и грибами.",
    price: 500,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("vareniki-potato-mushroom.jpg"),
    stock: 13,
    isVisible: true,
    sortOrder: 70
  },
  {
    id: "cherry-vareniki",
    categoryId: "stock",
    title: "Вареники с вишней",
    description: "Домашние вареники с сочной вишневой начинкой.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("vareniki-cherry.jpg"),
    stock: 10,
    isVisible: true,
    sortOrder: 80
  },
  {
    id: "cottage-strawberry-vareniki",
    categoryId: "stock",
    title: "Вареники с творогом и клубникой",
    description: "Домашние вареники с творогом и клубникой.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("vareniki-cottage-strawberry.jpg"),
    stock: 10,
    isVisible: true,
    sortOrder: 90
  },

  {
    id: "kids-soup-meatballs",
    categoryId: "kids",
    title: "Куриные фрикадельки для супа",
    description: "Куриные фрикадельки для быстрого домашнего супа.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("chicken-meatballs.jpg"),
    stock: 8,
    isVisible: true,
    sortOrder: 10
  },
  {
    id: "kids-rice-meatballs",
    categoryId: "kids",
    title: "Куриные тефтели с рисом",
    description: "Нежные куриные тефтели с рисом для быстрого обеда или ужина.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("chicken-meatballs.jpg"),
    stock: 11,
    isVisible: true,
    sortOrder: 20
  },
  {
    id: "lazy-pork-cabbage-rolls",
    categoryId: "kids",
    title: "Ленивые голубцы со свининой",
    description: "Домашние ленивые голубцы со свининой для быстрого ужина.",
    price: 700,
    unit: "kg",
    unitLabel: "1 кг",
    imageUrl: productImage("lazy-cabbage-rolls.jpg"),
    stock: 30,
    isVisible: true,
    sortOrder: 30
  }
];
